### ISSUE TITLE
GCC no longer builds on macOS 10.13

### ISSUE THREAD

**Issue by eproxus** [grisp/grisp-software#27]
Build fails with the `master` version of the toolchain on macOS 10.13.1. GCC fails to build with the error message:

```
...
arm-rtems4.12/eb/thumb/armv7-r/libstdc++-v3/include/bits/move.h:54:10: fatal error: type_traits: No such file or directory
 #include <type_traits> // Brings in std::declval too.
          ^~~~~~~~~~~~~
compilation terminated.
make[8]: *** [bad_array_new.lo] Error 1
make[8]: *** Waiting for unfinished jobs....
make[7]: *** [all-recursive] Error 1
make[6]: *** [all] Error 2
make[5]: *** [multi-do] Error 1
make[4]: *** [all-multi] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-target-libstdc++-v3] Error 2
make: *** [all] Error 2
shell cmd failed: /bin/sh -ex  /Users/alind/Stritzinger/Code/GRiSP/grisp-software/rtems-source-builder/rtems/build/arm-rtems4.12-gcc-7.1.0-newlib-2.5.0.20170623-x86_64-apple-darwin17.2.0-1/doit
error: building arm-rtems4.12-gcc-7.1.0-newlib-2.5.0.20170623-x86_64-apple-darwin17.2.0-1
```

This is a full `./build/build.sh` after running `git clean -fXd && git clean -fxd && git submodule sync && git submodule update`.

Full error report: [rsb-report-arm-rtems4.12-gcc-7.1.0-newlib-2.5.0.20170623-x86_64-apple-darwin17.2.0-1.txt](https://github.com/grisp/grisp-software/files/1513713/rsb-report-arm-rtems4.12-gcc-7.1.0-newlib-2.5.0.20170623-x86_64-apple-darwin17.2.0-1.txt)

Build tool details:

```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by eproxus** [comment]
Cannot confirm this anymore with the latest version of the toolchain and macOS 10.13.3.
